<?php
/**
 * ItemPartnerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\SalesOrderWOCharge
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sales Order Without Charge (A2X)
 *
 * In every API call, you can make use of the following operations:   - You can read entire sales orders without charge or only parts of the data, using the provided filters.   - You can create sales orders without charge. Note that you must use “deep insert” requests (a header plus the following entities: header partner, item and item partner). You cannot create entities without including any related entities.   - For existing sales orders without charge, you can create new items. Note that you must use “deep insert” requests (with the entity: item partner). You cannot create entities without including any related entities.   - For existing sales orders without charge, you can update the header, header partner, item and item partner.   - For existing sales orders without charge, you can delete the header, header partner, item and item partner.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\SalesOrderWOCharge\Test\Api;

use \BeLenka\SAP\SalesOrderWOCharge\Configuration;
use \BeLenka\SAP\SalesOrderWOCharge\ApiException;
use \BeLenka\SAP\SalesOrderWOCharge\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemPartnerApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\SalesOrderWOCharge
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemPartnerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aSalesOrderWithoutChargeItemSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemToPartnerGet
     *
     * Reads the item partners of a specific sales order without charge item..
     *
     */
    public function testASalesOrderWithoutChargeItemSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemToPartnerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerGet
     *
     * Reads the item partners for all sales order without charges..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionDelete
     *
     * Deletes the item partners of a specific item with a specific partner function in a specific sales order without charge..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionGet
     *
     * Reads the item partners of a specific item with a specific partner function in a specific sales order without charge..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionPatch
     *
     * Updates the item partners of a specific item with a specific partner function in a specific sales order without charge..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToItemGet
     *
     * Reads the sales order without charge item for a specific partner function of a sales order without charge item..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific partner function of a sales order without charge item..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
