<?php
/**
 * SalesOrderWithoutChargeHeaderApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\SalesOrderWOCharge
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sales Order Without Charge (A2X)
 *
 * In every API call, you can make use of the following operations:   - You can read entire sales orders without charge or only parts of the data, using the provided filters.   - You can create sales orders without charge. Note that you must use “deep insert” requests (a header plus the following entities: header partner, item and item partner). You cannot create entities without including any related entities.   - For existing sales orders without charge, you can create new items. Note that you must use “deep insert” requests (with the entity: item partner). You cannot create entities without including any related entities.   - For existing sales orders without charge, you can update the header, header partner, item and item partner.   - For existing sales orders without charge, you can delete the header, header partner, item and item partner.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\SalesOrderWOCharge\Test\Api;

use \BeLenka\SAP\SalesOrderWOCharge\Configuration;
use \BeLenka\SAP\SalesOrderWOCharge\ApiException;
use \BeLenka\SAP\SalesOrderWOCharge\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesOrderWithoutChargeHeaderApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\SalesOrderWOCharge
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesOrderWithoutChargeHeaderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aSalesOrderWithoutChargeGet
     *
     * Reads all sales order without charge headers..
     *
     */
    public function testASalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeItemSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific item..
     *
     */
    public function testASalesOrderWithoutChargeItemSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargePost
     *
     * Creates a sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeDelete
     *
     * Deletes a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeGet
     *
     * Reads the header of a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargePatch
     *
     * Updates a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeToItemGet
     *
     * Reads all items of a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeToItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeToItemPost
     *
     * Creates a sales order without charge item for a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeToItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeToPartnerGet
     *
     * Reads the header partners of a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeToPartnerGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSalesOrderWithoutChargeSalesOrderWithoutChargeToTextGet
     *
     * Reads the header texts of a specific sales order without charge..
     *
     */
    public function testASalesOrderWithoutChargeSalesOrderWithoutChargeToTextGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific partner function of a sales order without charge item..
     *
     */
    public function testASlsOrdWthoutChrgItmPartnerSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemPartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgItmTextSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemLanguageLanguageLongTextIDLongTextIDToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific text of a sales order without charge item..
     *
     */
    public function testASlsOrdWthoutChrgItmTextSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemLanguageLanguageLongTextIDLongTextIDToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgPartnerSalesOrderWithoutChargeSalesOrderWithoutChargePartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific header partner..
     *
     */
    public function testASlsOrdWthoutChrgPartnerSalesOrderWithoutChargeSalesOrderWithoutChargePartnerFunctionPartnerFunctionToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgSchedLineSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemScheduleLineScheduleLineToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific schedule line..
     *
     */
    public function testASlsOrdWthoutChrgSchedLineSalesOrderWithoutChargeSalesOrderWithoutChargeSalesOrderWithoutChargeItemSalesOrderWithoutChargeItemScheduleLineScheduleLineToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aSlsOrdWthoutChrgTextSalesOrderWithoutChargeSalesOrderWithoutChargeLanguageLanguageLongTextIDLongTextIDToSalesOrderWithoutChargeGet
     *
     * Reads the sales order without charge header for a specific header text..
     *
     */
    public function testASlsOrdWthoutChrgTextSalesOrderWithoutChargeSalesOrderWithoutChargeLanguageLanguageLongTextIDLongTextIDToSalesOrderWithoutChargeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
